- CHANGELOG.md
- package.json
- packages/core/package.json
- packages/immer/package.json
- packages/react/package.json
Increment monorepo package versions and update the CHANGELOG for version 0.5.7.
> release: v0.5.7

- CHANGELOG.md
- package.json
- packages/core/package.json
- packages/immer/package.json
- packages/react/package.json
Increment monorepo package versions and update the CHANGELOG for version 0.5.8.
> release: v0.5.8

- packages/react/src/classes/EvaluationStack.ts
- packages/react/test/integrations/atom-stores.test.tsx
The recent fix to make sure the default scheduler is restored whether or not the `evaluationFinished` mod is enabled (26d980b1eca3478bfdf7a1db1508261aa365c0b2) exposed a bug where the default scheduler would be restored as soon as any item in the evaluation stack is popped off.
Only restore the default scheduler when the _last_ item in the stack is popped off.
Also add a regression test that 💯% reproduces this and confirms the fix.
> fix(react): make all stores of all atoms in the evaluation stack use the ecosystem's scheduler

- CHANGELOG.md
- package.json
- packages/core/package.json
- packages/immer/package.json
- packages/react/package.json
Increment monorepo package versions and update the CHANGELOG for version 0.5.10.
> release: v0.5.10

- packages/core/src/types.ts
- packages/react/src/injectors/injectMachineStore.ts
The core package's `Observable` type was incompatible with RxJS observables. Fix that. Also add the current state's name to the inferred state names available on an individual MachineState.
core, react
> fix: improve `state.on` and `Observable` types

- packages/react/src/classes/index.ts
The SelectorCache class is documented, but not exported yet. This is necessary for type casting sometimes e.g. in ecosystem plugin modBus subscriptions when getting actions with payloads that can be either an atom instance or an atom selector. Export it.
> feat(react): export SelectorCache class

- docs/docs/api/classes/ZeduxPlugin.mdx
- packages/react/src/classes/Selectors.ts
- packages/react/src/classes/instances/AtomInstance.ts
- packages/react/src/utils/plugin-actions.ts
Plugins need access to selector create/destroy events so they can track the graph correctly. Rework the `statusChanged` mod to work with both atom instances and selectors. Update ZeduxPlugin docs to reflect this change.
> feat(react): make selectors trigger statusChanged mod events on init and destroy

- packages/react/src/types/index.ts
The `dehydrate` and `hydrate` atom config functions need to use a generic at the `atom()` factory level to really work. Maybe we'll get to this eventually, but for now just remove the not-good-enough `D` generics and use `any` and `unknown` types.
> fix(react): remove dehydrated state generic from ssr atom config options for now

- docs/docs/api/classes/Ecosystem.mdx
- packages/react/src/classes/Ecosystem.ts
- packages/react/src/classes/EvaluationStack.ts
- packages/react/src/classes/IdGenerator.ts
- packages/react/src/classes/instances/AtomInstance.ts
We generate timestamps/high-res timestamps in several places. These values end up in graph views and ecosystem dehydrations which is annoying for snapshot testing especially. Make all these calls go through a single method - `IdGenerator#now`. Now you only have to override the IdGenerator class's `generateId` and `now` methods to create fully-reproducible ids.
We may expand this someday to use functions or an IdGenerator-extending class that you pass to `createEcosystem`. Bu monkey-patching in test envs is good enough for now.
> feat(react): make timestamp generation easily overridable; fix statusChanged event order

- docs/docs/api/classes/Ecosystem.mdx
- docs/docs/api/classes/ZeduxPlugin.mdx
- packages/react/src/classes/Ecosystem.ts
- packages/react/src/classes/Graph.ts
- packages/react/src/hooks/useAtomSelector.ts
- packages/react/src/injectors/injectStore.ts
- packages/react/src/types/index.ts
- packages/react/test/integrations/__snapshots__/selection.test.tsx.snap
- packages/react/test/integrations/selection.test.tsx
- packages/react/test/utils/ecosystem.ts
In the process of filling out the test suite, I've found several checks (`if` statements, optional chaining operators, etc) that are completely unnecessary. Most of these are due to TS not knowing a situation is impossible. Prefer type casts to reduce build size and improve code branch coverage.
Also optimize a little more code for build size
> refactor(react): remove some unnecessary logic and cleanup code

- packages/react/src/classes/IdGenerator.ts
Firefox generates stack traces differently from Chrome/Safari. This makes `generateReactComponentId` throw an error. Make `generateReactComponentId` more resilient and handle Firefox specifically. These ids are unimportant but give better Dev X so we want to try to support them in DEV when possible.
Resolves #19
> fix(react): make DEV mode React component id generation work in SpiderMonkey

- packages/react/src/classes/Ecosystem.ts
- packages/react/src/classes/Scheduler.ts
We can be a little more robust when we hit a fatal error. Make the scheduler not hang forever in a running-but-not-running state. Also make `ecosystem.getInstance()` find/create the new, non-Destroyed instance when a Destroyed instance is passed.
> feat(react): wrap scheduler run in try...finally; add handling for destroyed instances

- packages/react/src/classes/Selectors.ts
- packages/react/src/hooks/useAtomSelector.ts
We don't need to be so picky about whether a selector is inline. The only danger we're trying to guard against is potentially giving selector graph nodes confusing names in very, very rare cases. Make these cases a tiny bit less rare and cut out a lot of ugly, non-performant code.
> feat(react): simplify inline selector detection

- docs/docusaurus.config.js
The docusaurus `editUrl` config is pointing to the repo root when it needs to point to the `/docs` path. Fix that. Also point the url to the github `/edit/` path instead of `/tree/`.
Resolves #24
> docs: fix docusaurus editUrl location and point it to a `/edit/` path

- packages/react/src/injectors/injectPromise.ts
The optional chaining of the `controller.abort('update')` calls in `injectPromise()` are causing builds to extract the `abort` function to its own variable, losing the `controller` `this` scope when invoked. This causes an `Illegal invocation` error.
Use an if statement instead and change the type cast location to match the other `controller.abort()` call.
> fix(react): prevent `controller.abort()` from isolating the `abort` fn

- CHANGELOG.md
- package.json
- packages/core/package.json
- packages/immer/package.json
- packages/react/package.json
Increment monorepo package versions and update the CHANGELOG for version 0.5.11.
> release: v0.5.11

- docs/docs/api/classes/AtomInstance.mdx
- docs/docs/api/classes/SelectorCache.mdx
- docs/docs/api/classes/ZeduxPlugin.mdx
- packages/react/src/classes/Ecosystem.ts
- packages/react/src/classes/EvaluationStack.ts
- packages/react/src/classes/Selectors.ts
- packages/react/src/classes/instances/AtomInstance.ts
- packages/react/src/classes/instances/AtomInstanceBase.ts
- packages/react/src/injectors/injectWhy.ts
- packages/react/src/utils/plugin-actions.ts
- packages/react/src/utils/types.ts
- packages/react/test/units/Selectors.test.tsx
We can simplify quite a bit of logic by reusing some property names between atom instances and selectors. Change the `evaluationFinished` mod to simply use `node` instead of different `instance` and `cache` keys.
Change `prevEvaluationReasons` and `_prevEvaluationResons` to simply `prevReasons`.
Change `nextEvaluationReasons` and `_nextEvaluationReasons` to simply `nextReasons`.
This includes making those fields non-underscore-prefixed in the `AtomInstance` class and therefore adding documentation for them.
This is a breaking change - the `evaluationFinished` mod event's payload shape has changed and some already-public fields in the `SelectorCache` class are renamed:
- `evaluationFinishedAction.payload.cache` -> `evaluationFinishedAction.payload.node`
- …
> feat(react)!: reuse names that can be shared between instances & selectors

- docs/docs/advanced/batching.mdx
- docs/docs/advanced/ssr.mdx
- docs/docs/api/injectors/injectCallback.mdx
- docs/docs/walkthrough/atom-apis.mdx
- packages/react/src/classes/AtomApi.ts
- packages/react/src/classes/instances/AtomInstance.ts
- packages/react/src/factories/api.ts
- packages/react/src/injectors/injectCallback.ts
- packages/react/test/integrations/batching.test.tsx
- packages/react/test/integrations/injectors.test.tsx
Automatically wrapping exported functions in `ecosystem.batch()` calls has some unwanted overhead. It also falls short in that those callbacks are sometimes called locally e.g. in `injectEffect()`. In this case they _won't_ batch, which is very confusing.
Make `injectCallback()` the auto-batcher instead. Auto-batching can be turned on by simply using it and turned off by not. It also makes `injectCallback()` finally hold a place in the codebase. It's been basically useless in Zedux till now - memoizing callbacks is not as important in Zedux as it is in React. Now it has a real use.
Also update tests and docs for the new functionality.
This is technically a breaking change. Exported functions that were relying on auto-batching and not using `injectCallback()` will not batch now, and …
> feat(react)!: move auto-batching from `api()` to `injectCallback()`

- docs/docs/api/classes/AtomInstance.mdx
- docs/docs/api/components/AtomProvider.mdx
- docs/docs/api/hooks/useAtomConsumer.mdx
- docs/docs/api/hooks/useAtomInstance.mdx
- docs/docs/walkthrough/react-context.mdx
- docs/sidebars.js
- packages/react/README.md
- packages/react/src/components/AtomProvider.tsx
- packages/react/src/components/index.ts
- packages/react/test/integrations/react-context.test.tsx
- packages/react/test/snippets/context.tsx
- packages/react/test/snippets/ions.tsx
- packages/react/test/snippets/selectors.tsx
Since revising the concept of an "atom" in Zedux to mean "atom instance" instead of "atom template", the `AtomInstanceProvider` component is unnecessarily verbose. `AtomProvider` now means the same thing and looks so much cleaner.
We are keeping the word `instance` in most APIs to avoid confusion, but it isn't necessary here since `AtomProvider` has a required `instance` or `instances` prop.
This is a breaking change - the component has been renamed. Import and use `AtomProvider` now:
```tsx
- import { AtomInstanceProvider } from '@zedux/react' // before
+ import { AtomProvider } from '@zedux/react' // after
- <AtomInstanceProvider instance={instance}><Child /></AtomInstanceProvider> // before
+ <AtomProvider instance={instance}><Child /></AtomProvider> // after
```
> feat(react)!: AtomInstanceProvider -> AtomProvider

- docs/docs/api/classes/AtomInstance.mdx
- docs/docs/api/components/AtomProvider.mdx
- docs/docs/api/hooks/useAtomContext.mdx
- docs/docs/api/hooks/useAtomInstance.mdx
- docs/docs/walkthrough/react-context.mdx
- docs/sidebars.js
- packages/react/README.md
- packages/react/src/components/AtomProvider.tsx
- packages/react/src/hooks/index.ts
- packages/react/src/hooks/useAtomContext.ts
- packages/react/test/integrations/react-context.test.tsx
- packages/react/test/snippets/context.tsx
- packages/react/test/snippets/ions.tsx
- packages/react/test/snippets/selectors.tsx
Zedux using the word `Consumer` instead of `Context` is an unnecessary discrepancy between Zedux's API and React's. Rename `useAtomConsumer` to `useAtomContext`.
Also update all docs and tests.
This is a breaking change. Import and use `useAtomContext` instead of `useAtomConsumer` now:
```ts
- import { useAtomConsumer } from '@zedux/react' // before
+ import { useAtomContext } from '@zedux/react' // after
- const instance = useAtomConsumer(myAtom) // before
+ const instance = useAtomContext(myAtom) // after
```
> feat(react)!: useAtomConsumer -> useAtomContext

- docs/docs/api/classes/AtomTemplate.mdx
- docs/docs/api/classes/Ecosystem.mdx
- docs/docs/api/types/AtomInstanceTtl.mdx
- docs/docs/api/types/EcosystemConfig.mdx
- docs/docs/walkthrough/configuring-atoms.mdx
- packages/atoms/src/classes/Ecosystem.ts
- packages/atoms/src/classes/instances/AtomInstance.ts
- packages/atoms/src/types/index.ts
- packages/react/test/integrations/lifecycle.test.tsx
We want to add more atom defaults at the ecosystem level in the future besides `defaultTtl`. Rework this atom config option. Make it an `atomDefaults` object with an optional `ttl` property (that's all for now).
This is a breaking change. The `defaultTtl` ecosystem config option doesn't exist anymore. Set `atomDefaults.ttl` instead:
```ts
- createEcosystem({ defaultTtl: 0 })
+ createEcosystem({ atomDefaults: { ttl: 0 } })
- <EcosystemProvider defaultTtl={0}><Child /></EcosystemProvider>
+ <EcosystemProvider atomDefaults={{ ttl: 0 }}><Child /></EcosystemProvider>
```
> feat(atoms)!: `defaultTtl` -> `atomDefaults.ttl`

- packages/core/src/api/createStore.ts
- packages/core/test/integrations/store-composition.test.ts
All store updates currently go through the scheduler. Most updates don't need to - the scheduler is only used to sort out updates between composed stores. Most stores in a real app don't use store composition, so going through the scheduler is an unnecessary performance loss in most situations.
The scheduler is very fast, but skipping it is even faster, by about ~28% according to the following tests:
```ts
import { createStore } from '@zedux/core'
const store = createStore(null, 0)
const start = performance.now()
for (let i = 1; i < 1000000; i++) {
store.setState(i)
}
console.log('time:', performance.now() - start)
```
```ts
import { atom, createEcosystem } from '@zedux/atoms'
const ecosystem = createEcosystem()
const atom1 = atom('1', 0)
const instance1 = ecosystem.getInstance(atom1) …
```
> refactor(core): improve store update perf in non-composed stores by ~28%

- docs/docs/advanced/more-patterns.mdx
- docs/docs/api/factories/api.mdx
- docs/docs/api/factories/atom.mdx
- docs/docs/api/factories/ion.mdx
- docs/docs/api/injectors/injectPromise.mdx
- packages/atoms/src/classes/AtomApi.ts
- packages/atoms/src/classes/instances/AtomInstance.ts
- packages/atoms/src/factories/api.ts
- packages/atoms/src/factories/atom.ts
- packages/atoms/src/factories/ion.ts
- packages/atoms/src/injectors/injectPromise.ts
- packages/atoms/src/types/atoms.ts
- packages/atoms/src/types/index.ts
- packages/react/test/types.test.tsx
The AtomApi class has almost all the same generics as Atoms. Update it to use a new `AtomApiGenerics` type map, similar to the `AtomGenerics` type map. Add an `AnyAtomApi` type helper. Update all relevant type helpers to accept `AnyAtomApi` too. Also update docs, improve the `.addExports()` method return type, prettify the return types of the AtomApi methods, and add a new test.
This is technically a breaking change, but only for TS users. No code is changing in the builds.
Now when typing AtomApis manually, use the type map instead of ordered generics:
```ts
- type Example = AtomApi<State, Exports, StoreType, PromiseType>
+ type Example = AtomApi<{ Exports: Exports; Promise: PromiseType; State: State; Store: StoreType }>
```
> feat(atoms)!: implement AtomApiGenerics type map and all its helpers

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
Increment monorepo package versions and update the CHANGELOG for version 1.0.0-rc.0.
> release: v1.0.0-rc.0

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
Increment monorepo package versions and update the CHANGELOG for version 1.0.0.
> release: v1.0.0

- README.md
- docs/docs/walkthrough/quick-start.mdx
- packages/react/package.json
- packages/react/src/components/EcosystemProvider.tsx
- packages/react/src/hooks/useAtomInstance.ts
- packages/react/src/hooks/useAtomSelector.ts
- yarn.lock
Some apps are still using React versions < 18. Prefer using the [`useSyncExternalStore` shim](https://www.npmjs.com/package/use-sync-external-store) for now.
This shim adds over 1kb to the minified build. I'd say it's worth it for now, but something to consider.
Resolves #44
> fix(react): use `useSyncExternalStore` shim for now

- docs/blog/atoms-the-happy-medium.md
- docs/blog/how-atoms-fixed-flux.md
- packages/atoms/src/classes/Ecosystem.ts
- packages/atoms/src/classes/IdGenerator.ts
- packages/atoms/src/classes/Selectors.ts
- packages/atoms/test/units/IdGenerator.test.tsx
- packages/react/src/hooks/useAtomSelector.ts
- packages/react/test/integrations/__snapshots__/selection.test.tsx.snap
- packages/react/test/integrations/params.test.tsx
- packages/react/test/integrations/selection.test.tsx
- packages/react/test/snippets/stress-testing.tsx
- packages/react/test/units/Selectors.test.tsx
- packages/react/test/units/useAtomSelector.test.tsx
- packages/react/test/utils/console.ts
There's an edge case with AtomSelector id generation where if two different selectors have the same name and take the same params, they'll reuse the same cache. Improving the code responsible for this has been a tech debt item since the selectors graph rework, but this is the first time we've run into a problem from it.
Improve id generation in the `IdGenerator`. Make new selector references always generate a new base key id hash for their ids so no conflicts like this can happen in the future. Make ids smaller _and_ more unique by using a radix of 36. Clean up some code, finally addressing this tech debt and fixing the cache reuse bug in the process.
> fix(atoms): improve id generation; prevent selector with args cache reuse edge case

- packages/atoms/src/classes/AtomApi.ts
TS struggles breaking down an AtomApi's type when chained methods (e.g. `.setPromise()`, `.setExports()`, etc) are called and extra layers are added (e.g. put the whole thing in a function called in a component and pass more inferred types - at least that's the general idea).
The `Prettify` helper doesn't need to wrap the whole class. Make it only wrap the Omit. This apparently drastically reduces the work TS has to do.
> fix(atoms): make it easier for TS to infer AtomApi types from chained methods

- packages/atoms/src/classes/Ecosystem.ts
- packages/atoms/src/injectors/injectAtomInstance.ts
- packages/atoms/src/injectors/injectAtomState.ts
- packages/atoms/src/injectors/injectAtomValue.ts
- packages/atoms/src/types/index.ts
- packages/react/src/hooks/useAtomInstance.ts
- packages/react/src/hooks/useAtomState.ts
- packages/react/src/hooks/useAtomValue.ts
- packages/react/test/types.test.tsx
The `ParamlessTemplate` type helper is good enough in most situations, however there are some exceptions. Namely, when declaring a function that accepts only paramless atom templates (singletons) for simplicity reasons, the types don't "just work" and require an extra cast:
```ts
function noParams<A extends AnyAtomTemplate<{ Params: [] }>>(atom: A) {
return myEcosystem.get(atom) // Error! Even though we know the params are `[]`
}
```
This PR fixes that. The above code will no longer error.
atoms, react
> fix: improve overloads of atom-template-accepting functions for paramless atoms

- packages/atoms/src/classes/Ecosystem.ts
- packages/react/src/components/AtomProvider.tsx
- packages/react/src/hooks/useAtomContext.ts
- packages/react/src/utils.ts
The atoms package still has one usage of React - creating and storing React context objects in the ecosystem. Move that logic to the atoms package and provide a general storage mechanism for internal packages to store anything at the ecosystem level.
atoms, react
> feat: make atoms package fully framework agnostic

- packages/atoms/src/classes/Graph.ts
- packages/atoms/src/types/index.ts
- packages/react/test/integrations/__snapshots__/selection.test.tsx.snap
- packages/react/test/integrations/graph.test.tsx
There are several places where we don't have to call `Object.keys()`. In some stress tests, these can be called a lot, resulting in lots of overhead.
Remove 2 of these `Object.keys()` calls in the graph - when scheduling and unscheduling node destruction. Instead add a `refCount` counter that we manually keep in sync with the dependents count.
> feat(atoms): improve graph perf by removing unnecessary `Object.keys()` calls

- packages/react/src/components/EcosystemProvider.tsx
- packages/react/src/hooks/useAtomInstance.ts
- packages/react/src/hooks/useAtomSelector.ts
- scripts/build.js
React's `react/jsx-runtime` auto-added imports are auto-added wrong in esm builds. Make it specify the file extension. Also make the `useSyncExternalStore` shim imports do the same.
> fix(react): make React imports specify file extensions in esm builds

- packages/react/package.json
- packages/react/vite.config.ts
- tsconfig.json
I plugged in the `useSyncExternalStore` shim but forgot to update the `react` package's React peer dep. Zedux should now be compatible with React v16.3.0 and up (the version that introduced the new context API)
> fix(react): update React peer dep to a minimum of v16.3.0

- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
The `default` field in the `package.json` files of all packages should be the last one declared - including after the nested `production` key. Fix that for all packages.
atoms, core, immer, machines, react
> fix: fix package.json export order

- packages/atoms/src/classes/Ecosystem.ts
- packages/react/test/units/Ecosystem.test.tsx
`ecosystem.findAll()` currently has a bug where it doesn't find a match if a string key with uppercase letters is passed. The simple workaround has been to `.toLowerCase()` the string before passing, but it's time we fixed it for real.
Also improve string searching in `ecosystem.find()` by returning the exact match if there is one, rather than the first match.
> fix(atoms): improve atom searching

- packages/atoms/src/classes/AtomApi.ts
- packages/react/test/types.test.tsx
The `.setPromise()` method currently only accepts a promise. This can be a little annoying to work with e.g. when using inline expressions to conditionally set the promise. Allow such expressions to resolve to `undefined` and make the types correctly reflect that an atom with such a returned api has a `Promise: undefined` type.
> feat(atoms): allow setting promise to undefined in AtomApi

- packages/atoms/src/classes/Ecosystem.ts
- packages/atoms/src/classes/templates/AtomTemplateBase.ts
- packages/react/test/units/Ecosystem.test.tsx
When using JS (non-TS), it's much easier to forget to pass something. It's ugly seeing Zedux throw errors from trying to use undefined values, etc. Throw helpful error messages instead in the most common case - when a non-template/instance is passed (directly or indirectly) to `ecosystem.getInstance()`
> feat(atoms): improve non-TS `.getInstance()` usage by throwing helpful errors

- packages/atoms/src/classes/Ecosystem.ts
- packages/atoms/src/classes/EvaluationStack.ts
- packages/atoms/src/classes/Graph.ts
- packages/atoms/src/classes/Selectors.ts
- packages/atoms/src/classes/instances/AtomInstance.ts
- packages/atoms/src/injectors/injectStore.ts
- packages/atoms/src/types/index.ts
- packages/core/src/api/createStore.ts
- packages/immer/src/injectImmerStore.ts
- packages/machines/src/injectMachineStore.ts
- packages/react/src/hooks/useAtomInstance.ts
- packages/react/src/hooks/useAtomSelector.ts
- packages/react/test/integrations/__snapshots__/graph.test.tsx.snap
- packages/react/test/integrations/__snapshots__/selection.test.tsx.snap
- packages/react/test/integrations/graph.test.tsx
Use maps instead of objects for tracking graph dependencies and dependents. These are much faster to iterate over according to [this benchmark](https://jsbench.me/49lhtusot1/1). Some local testing shows that these changes increase speed by up to 4x in some cases.
Also set the `store._isSolo` property instead of deriving it for a tiny speed gain. Also set the `instance._isEvaluating` property instead of deriving it from the evaluation stack for even more tiny speed gains.
Also improve bundle size a little bit.
atoms, core, immer, machines, react
> refactor: micro-optimize store and graph operations

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
Increment monorepo package versions and update the CHANGELOG for version 1.0.2.
> release: v1.0.2

- packages/atoms/src/injectors/injectPromise.ts
- packages/react/test/integrations/promises.test.tsx
`injectPromise()` currently clears the previous `.data` when the promise factory reruns. This is inconsistent with how query atoms work and isn't useful.
Make `.data` persist across reruns.
> fix(atoms): make data retention consistent across `injectPromise` and `api(promise)`

- packages/atoms/src/classes/Selectors.ts
- packages/react/test/integrations/__snapshots__/selection.test.tsx.snap
- packages/react/test/units/Selectors.test.tsx
Selectors with params can have multiple selector cache entries reusing the same `_refBaseKeys` entry. When one of these selectors is destroyed, it shouldn't delete the `_refBaseKeys` WeakMap entry - other selector caches could still be using it. Let the WeakMap clean up after itself instead.
> fix(atoms): let the WeakMap clean up selector ref keys

- packages/atoms/src/classes/instances/AtomInstance.ts
- packages/react/test/integrations/promises.test.tsx
#65 made `injectPromise` retain the `.data` property during refetch. Query atoms apparently still don't have this functionality. Change that.
> fix(atoms): make query atoms retain data

- docs/docs/api/injectors/injectPromise.mdx
- packages/atoms/src/injectors/injectPromise.ts
- packages/atoms/src/injectors/injectWhy.ts
- packages/atoms/src/types/index.ts
- packages/react/test/integrations/promises.test.tsx
With query atoms, calling `instance.invalidate()` reevaluates the atom, thus recreating the promise. When migrating from a query atom to using `injectPromise` (a common task when more power is needed), `instance.invalidate()` is no longer sufficient to make the promise rerun.
There are many workarounds, but all are pretty inconvenient. This PR adds a `runOnInvalidate` config option to `injectPromise` itself to get the query atom behavior back.
```ts
const myPromiseAtom = atom(
'myPromise',
() => injectPromise(myPromiseFactory, [], { runOnInvalidate })
)
const myPromiseInstance = myEcosystem.getInstance(myPromiseAtom)
// now this will cause `myPromiseFactory` to rerun, updating the store's loading status:
myPromiseInstance.invalidate()
```
> feat(atoms): add `runOnInvalidate` option to `injectPromise`

- docs/docs/api/injectors/injectInvalidate.mdx
- packages/atoms/src/injectors/injectInvalidate.ts
Since we introduced `injectSelf`, `injectInvalidate` isn't necessary. Deprecate it. We'll plan to remove it in Zedux v2.
Use the following pattern instead:
```ts
const self = injectSelf()
// then in a callback or effect:
self.invalidate()
```
> feat(atoms): deprecate `injectInvalidate` (prefer `injectSelf`)

- packages/atoms/src/classes/instances/AtomInstance.ts
- packages/atoms/src/injectors/injectStore.ts
- packages/immer/src/injectImmerStore.ts
- packages/machines/src/injectMachineStore.ts
- packages/react/test/integrations/ssr.test.tsx
`injectStore` and similar store-injecting injectors shouldn't call `ecosystem._consumeHydration()` when their `hydrate` option is true since that breaks injector composability. Instead, always call `ecosystem._consumeHydration()` once, after evaluation is over. This allows all injectors that want it to receive the hydration.
@affects atoms, immer, machines
> fix: prevent injectors from consuming hydrations

- packages/react/src/utils.ts
React complains about the same React context object being used by multiple "renderers" (react-dom instances in this case) when Zedux shares context objects across windows in multi-window setups. Instead, create a different context object for each instance of React that Zedux runs in. Use the React instance's `createContext` function to key a WeakMap mapped to the record of cached context objects.
> fix(react): fix multiple renderers cross-window React warning

- packages/core/package.json
As discussed in #74, the core package's `main` package.json field is pointing to an old file that doesn't exist anymore. Most bundlers should be resolving the `exports.require` or `exports.default` field instead, but Metro isn't. This should be updated anyway, so do it.
> fix(core): point core package's  field to the correct file

- packages/core/src/api/createStore.ts
- packages/core/test/integrations/registrations.test.ts
After lots of stress testing, one of Zedux's (relatively small) performance bottlenecks in very extreme cases is the `createStore`'s cloning of the subscribers array on every dispatched action. This array is very small in Zedux stores since most "subscriptions" are handled by the atom graph.
We clone the subscribers to prevent mid-iteration mutation (deletion specifically) from causing a non-deleted subscriber to be skipped in the notify-subscribers loop. If we don't clone, then we'll have to prevent mutation by other subscribers. This means the `.subscribe()` method will have to either schedule its subscription to be added when notify-subscribers is over or it will have to replace the array ref, performing a clone itself, which will slow down subscription adding and deleting.
After lots …
> feat(core): micro-optimize iterating and removing store subscribers

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
Increment monorepo package versions and update the CHANGELOG for version 1.1.0-rc.0.
> release: v1.1.0-rc.0

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
Increment monorepo package versions and update the CHANGELOG for version 1.1.0.
> release: v1.1.0

- packages/atoms/src/classes/instances/AtomInstance.ts
- packages/atoms/src/classes/templates/AtomTemplate.ts
- packages/react/test/types.test.tsx
For TypeScript users, an atom instance's template type (e.g. when using `instance.template`) is inferred to be an instance of the Zedux built-in `AtomTemplate` class. But if the instance was created from a custom class that extends `AtomTemplate`, the type information of that child class would be lost. For example:
```ts
class MyTemplate extends AtomTemplate {
public customMethod() {
// ... implemention ...
}
}
const myCustomTemplateAtom = new MyTemplate('myCustomTemplate', () => 'example state')
const instance = ecosystem.getInstance(myCustomTemplateAtom)
instance.template.customMethod() // actually works! But TS used to complain
```
Now TS doesn't complain; the type information of the instance's actual atom template is retained
> feat(atoms): give atom instances access to their real template type

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
Increment monorepo package versions and update the CHANGELOG for version 1.1.1.
> release: v1.1.1

- README.md
- packages/atoms/src/classes/IdGenerator.ts
- packages/atoms/src/classes/Selectors.ts
- packages/react/package.json
- packages/react/src/components/EcosystemProvider.tsx
- packages/react/src/hooks/useAtomInstance.ts
- packages/react/src/hooks/useAtomSelector.ts
- packages/react/src/hooks/useReactComponentId.ts
- packages/react/test/integrations/__snapshots__/ecosystem.test.tsx.snap
- packages/react/test/integrations/__snapshots__/graph.test.tsx.snap
- packages/react/test/integrations/selection.test.tsx
- packages/react/test/integrations/suspense.test.tsx
- packages/react/test/units/useAtomSelector.test.tsx
- packages/react/test/utils/renderInEcosystem.tsx
- yarn.lock
React 18 broke `useAtomSelector` in strict mode. This is because of lots of quirks with `useSyncExternalStore` that I coded circles around in React 17.
Stop fighting with `useSyncExternalStore`. It still has many quirks, doesn't solve any of the problems we wanted it to solve, and most importantly looks to be poorly supported by the React team - for example, transitions will likely never be supported.
Remove `useSyncExternalStore` usages. Instead,
- add graph edges during render in `useAtomInstance`, handling strict mode double-renders and double-effect-invocations specifically. The impure operations are completely idempotent  since generated ids are consistent for a given component thanks to `useId`
- add a simple `useEffect` in `EcosystemProvider`
- run selectors statically during …
> feat: remove uSES usages and support strict mode

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
Increment monorepo package versions and update the CHANGELOG for version 1.2.0-rc.0.
> release: v1.2.0-rc.0

- packages/react/src/hooks/useAtomSelector.ts
- packages/react/test/units/__snapshots__/useAtomSelector.test.tsx.snap
- packages/react/test/units/useAtomSelector.test.tsx
The recent `useAtomSelector` changes to move off of `useSyncExternalStore` for #83 introduced a bug with inline atom selectors that return referentially unstable results on every run. Handle that case specifically and add tests - one for strict mode on, one for strict mode off.
> fix(react): handle unstable inline selector results in `useAtomSelector`

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
Increment monorepo package versions and update the CHANGELOG for version 1.2.0-rc.1.
> release: v1.2.0-rc.1

- packages/react/src/components/AtomProvider.tsx
`AtomProvider` doesn't have to use the once-dead-now-okay-again-but-meh `React.FC` type. Remove it.
> fix(react): improve types for AtomProvider

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
Increment monorepo package versions and update the CHANGELOG for version 1.2.0.
> release: v1.2.0

- packages/core/src/api/createStore.ts
- packages/core/test/units/Store.test.ts
We've had a TODO to maybe inform effects subscribers when `Store#setState` or `Store#setStateDeep` are called but don't change state. We've finally figured out the behavior that's needed in this situation.
Short-circuiting is fine when state hasn't changed _unless_ metadata is passed (e.g. `setState(newState, metadataHere)`. When metadata is passed, the action should always proceed to all parent/child stores and notify all effects subscribers of the pseudo-action with its `meta` property.
> fix(core): always notify effects subscribers when a hydration has metadata

- packages/core/src/api/createStore.ts
- packages/core/src/types.ts
- packages/core/test/types.test.tsx
- packages/react/test/types.test.tsx
When extending the core `Store` class and instantiating your class with an array type, TS gives a super cryptic error message that basically boils down to: `store.use()` doesn't accept a hierarchy descriptor type where the `State` generic is an array.
Make `store.use()` accept a different type that infers the hierarchy descriptor type better since it's know at that point. Prevent the new type's union from containing `Branch` if the state type at a given level is an array. Even though `store.use()` technically allows swapping an array out for more nested objects, there should never be a real use case for that and TS land really doesn't need to know about it.
`store.use()` wasn't designed with TS in mind. It used to be the primary mechanism for code-splitting in Zedux before atoms. Now it's …
> fix(core): allow store-extending classes to have array state types

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
Increment monorepo package versions and update the CHANGELOG for version 1.2.1.
> release: v1.2.1

- packages/atoms/src/classes/Graph.ts
- packages/atoms/src/classes/Selectors.ts
- packages/react/src/hooks/useAtomSelector.ts
- packages/react/test/integrations/selection.test.tsx
- packages/react/test/units/__snapshots__/useAtomSelector.test.tsx.snap
- packages/react/test/units/useAtomSelector.test.tsx
When `useAtomSelector`'s `useEffect`'s cleanup function runs, it can destroy any `ttl: 0` atoms before the `useEffect` body generates the new cached selector that should be keeping those atoms around.
While this extra destruction/recreation shouldn't usually cause problems, it can lead to a bug when such an atom is created outside React, given updated state, and then subscribed to by only the selector that is then destroyed. The best practice is to not give `ttl` (especially not `ttl: 0`) to atoms you intend to pre-cache or manage outside React. But still, Zedux can at least not make things worse in this case.
Use `queueMicrotask` very strategically to work around React's timing here. Defer cleanup of the old selector cache until the new effect run has subscribed to the new selector …
> fix: useAtomSelector - subscribe to the new selector before destroying the old

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
Increment monorepo package versions and update the CHANGELOG for version 1.2.2-rc.0.
> release: v1.2.2-rc.0

- packages/atoms/src/classes/Ecosystem.ts
- packages/react/test/units/Ecosystem.test.tsx
The recent change to add fuzzy search to `ecosystem.find()` (#79) made the search too fuzzy. Specifically, when atom params are passed to `ecosystem.find() , it's never expected that anything but an exact match is returned. Disable fuzzy search when params are passed.
I'm categorizing this as a bug fix, since the overtly-fuzzy search wasn't expected behavior. But it's also a new feature - e.g. now when passing a search string as the first param, you can pass an empty array as the second param to only return an exact match (or undefined if no match).
> fix(atoms): disable `ecosystem.find()` fuzzy search if params are passed

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
Increment monorepo package versions and update the CHANGELOG for version 1.2.2.
> release: v1.2.2

- .vscode/launch.json
- jest.setup.ts
- packages/atoms/src/classes/Selectors.ts
- packages/machines/test/integrations/state-machines.test.tsx
- packages/machines/test/snippets/api.tsx
- packages/react/src/hooks/useAtomInstance.ts
- packages/react/src/hooks/useAtomSelector.ts
- packages/react/test/integrations/__snapshots__/selection.test.tsx.snap
- packages/react/test/integrations/selection.test.tsx
- packages/react/test/units/Selectors.test.tsx
- packages/react/test/units/__snapshots__/useAtomSelector.test.tsx.snap
- packages/react/test/units/useAtomSelector.test.tsx
- packages/react/test/utils/ecosystem.ts
`useAtomSelector` has had to jump through so many hoops to support React 18. Some of these hoops have caused such ugly code that edge cases are possible. We've seen one that we can't reproduce consistently, but it comes down to React scheduling `useEffect` microtasks for a newly mounted component tree at different points in time that interweave with `useAtomSelector`'s `queueMicrotask` calls inside its `useEffect`s in that same component tree.
`useAtomSelector` has to support React StrictMode (and concurrent mode and everything StrictMode prepares for) while handling inline selectors, selectors that return referentially unstable results, and of course the old problematic React behavior of unmounting a component tree after the new tree has rendered, but before its effects have run.
This is …
> fix: optimize `useAtomSelector` for React 19

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
Increment monorepo package versions and update the CHANGELOG for version 1.3.0-rc.0.
This PR was generated by the release script at https://github.com/Omnistac/zedux/tree/next/v1.3.x/scripts/release.js
> release: v1.3.0-rc.0

- packages/react/src/hooks/useAtomSelector.ts
- packages/react/test/units/useAtomSelector.test.tsx
The new `useAtomSelector` implementation had a copy-paste error - when setting `mounted` to false temporarily while swapping out inline refs, the code never actually set it back to true, instead setting it to false again. This meant inline selectors would lose their subscription after the 2nd update (it would go: First render, first update, second render, swap ref and destroy subscription). No test cases and my simple testing never checked beyond the second render.
Add a regression test for this that makes sure inline selectors stay subscribed across four renders.
> fix(react): restore `useAtomSelector` mounted state when swapping inline refs

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
Increment monorepo package versions and update the CHANGELOG for version 1.3.0-rc.1.
This PR was generated by the release script at https://github.com/Omnistac/zedux/tree/next/v1.3.x/scripts/release.js
> release: v1.3.0-rc.1

- packages/atoms/src/classes/Selectors.ts
- packages/react/src/hooks/useAtomSelector.ts
- packages/react/test/integrations/__snapshots__/selection.test.tsx.snap
- packages/react/test/units/Selectors.test.tsx
- packages/react/test/units/useAtomSelector.test.tsx
With the new changes to `useAtomSelector`, we can optimize the `useEffect` to only rerun when the cache id changes, not the cache object reference. This makes `useAtomSelector` even more closely mimic `useAtomInstance` which has been a beautifully stable piece of code for a long time now.
This actually fixes an rerender loop bug that I originally attempted to address by going back to deleting the ref from the Selector class's weak map on selector destroy. But that approach doesn't work because it deletes the ref that may still be in use by other caches of the same selector ref that have different params. Add a test case for this so we never regress again.
> fix(react): only rerun `useAtomSelector` effect on cache id change

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
Increment monorepo package versions and update the CHANGELOG for version 1.3.0-rc.2.
This PR was generated by the release script at https://github.com/Omnistac/zedux/tree/next/v1.3.x/scripts/release.js
> release: v1.3.0-rc.2

- packages/atoms/src/classes/Selectors.ts
- packages/react/src/hooks/useAtomSelector.ts
- packages/react/test/units/useAtomSelector.test.tsx
`useAtomSelector`'s failsafe `queueMicrotask` is a little too aggressive and can (very rarely) lead to race conditions with React's own queued microtasks. #106 and Zedux v1.3.x already fix this for React 19, but React 18 is still the current version and still needs a better (temporary) fix.
Use `requestIdleCallback` (falling back to `setTimeout` in node) instead of `queueMicrotask`. This means (in StrictMode in React 18) that some leaked selector nodes will be visible for a short time before Zedux circles back and cleans them up, but it's better than being too aggressive and cleaning up graph edges that shouldn't be.
> fix(react): make `useAtomSelector` wait for idle time to do failsafe cleanup

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
Increment monorepo package versions and update the CHANGELOG for version 1.2.3.
> release: v1.2.3

- packages/react/package.json
- packages/react/src/hooks/useReactComponentId.ts
- packages/react/test/integrations/ecosystem.test.tsx
- packages/react/test/integrations/react-context.test.tsx
- packages/react/test/integrations/suspense.test.tsx
- packages/react/test/units/__snapshots__/useAtomSelector.test.tsx.snap
- packages/react/test/units/useAtomSelector.test.tsx
- yarn.lock
Since React 19 resolves the big issue that has made Zedux's `useAtomSelector` hook so complex in the past, Zedux v1.3.0 and v2.0.0 (and all future versions) will _technically_ drop support for React versions prior to 19.
Using Zedux in older versions will technically work, so we aren't labeling this as a breaking change or waiting till Zedux v2. However, it will be susceptible to a memory "leak" when using `useAtomSelector`. This isn't a real leak since Zedux gives you full control over the cache. This means you can set up e.g. an interval that regularly destroys cached selectors that have no dependents. For example:
```ts
const runCleanup = () => requestIdleCallback(() => {
const graph = myEcosytem.viewGraph()
Object.entries(myEcosystem.selectors.findAll()).forEach(([id, cache]) => {
if …
```
> feat(react): upgrade peer and dev deps to React 19

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
Increment monorepo package versions and update the CHANGELOG for version 2.0.0-alpha.0.
> release: v2.0.0-alpha.0

- packages/react/package.json
Zedux doesn't actually require React v19, it just has a memory leak vulnerability in `useAtomSelector` in older versions when unstable function references are passed.
Since there are valid workarounds for React 18, we shouldn't require v19 in our peer dep. For now anyway.
See [this discussion](https://github.com/Omnistac/zedux/discussions/123#discussioncomment-10930354)
> chore(react): relax React peer dep for now - use `>=18`

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
Increment monorepo package versions and update the CHANGELOG for version 2.0.0-alpha.1.
> release: v2.0.0-alpha.1

- packages/react/package.json
- packages/react/test/integrations/suspense.test.tsx
- packages/react/test/utils/renderInEcosystem.tsx
- yarn.lock
#125 never made it into the v1 branch. Also, now that React 19 is officially out, we can update our `react` and `react-dom` dev deps, peer deps, and the dev deps of their respective types packages.
Update those. Also, React 19 slightly changed the format of one log message since the RC we were on previously. So fix 2 tests that relied on the old output.
> chore(react): update react deps with React 19

- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
@affects atoms, core, immer, machines, react
The node resolver chooses the first package.json export that matches. Since the "production" export was not listed first, it has effectively not been in use (at least when using the node resolver and any tooling that adheres to that resolving strategy). Much more of a write-up and how I ran into this in https://github.com/nitrojs/nitro/issues/2923
I've adjusted the exports to move "production" to the first position. 
That said - is there a reason to ship the minified files at all? Why not remove the complexity here and allow downstream consumers to consume as is (node) or minify w their existing build pipeline (vite, swc, etc)? Better stack traces / debugging is a major benefit to downstream consumers importing a non-minified version of zedux.
> fix: remove package.json production exports

- packages/react/src/hooks/useReactComponentId.ts
In reviewing the current state of the `v1.x` branch preparatory to publishing a new v1 minor version, I determined that the `useReactComponentId` hook is too optimistically assuming it'll be used in React 19. While this doesn't break anything when used with React 18, it does mean poorer dev X since components will add generic ids to the atom graph. Zedux v1 is supposed to be completely compatible with React 18, so I think it should still support this dev X.
To be clear, v2 will work with React 18 as well, but with some caveats. The dev X of seeing the component name that added a graph dependency in Zedux is not something that React itself officially supports. So I'm fine with this change being omitted in v2. When upgrading to Zedux v2, we'll recommend to also upgrade to React 19 to get …
> fix(react): fallback to React 18 internals for getting component names

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
Increment monorepo package versions and update the CHANGELOG for version 1.3.0.
> release: v1.3.0

- jest.config.ts
- package.json
- yarn.lock
Zedux is still using Typescript v4.4 internally. This should be well behind any of our users. It's time to upgrade to the v5 line. There should be no problem with upgrading directly to the latest version, v5.7.2.
This will unlock some new features for future Zedux APIs, such as the upcoming `As<type>` runtime util for defining signal event types.
> chore: upgrade to typescript v5.7

- packages/immer/package.json
- packages/immer/src/ImmerStore.ts
- yarn.lock
Immer v10 removed the default `produce` export. The `@zedux/immer` package claims to be compatible with all versions of immer above 9.0.19, but it's still using the default `produce` export. Update to use the named `produce` export instead which works in both immer v9 and v10.
Resolves #145
> fix(immer): import named `produce` export from immer

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
- packages/stores/package.json
Increment monorepo package versions and update the CHANGELOG for version 2.0.0-beta.0.
> release: v2.0.0-beta.0

- packages/atoms/src/classes/GraphNode.ts
- packages/atoms/src/classes/IdGenerator.ts
- packages/atoms/src/classes/instances/AtomInstance.ts
- packages/atoms/src/types/index.ts
- packages/atoms/src/utils/evaluationContext.ts
- packages/react/test/__snapshots__/types.test.tsx.snap
- packages/react/test/integrations/__snapshots__/selection.test.tsx.snap
- packages/react/test/stores/__snapshots__/graph.test.tsx.snap
- packages/react/test/stores/graph.test.tsx
- packages/react/test/units/__snapshots__/SelectorInstance.test.tsx.snap
- packages/react/test/units/__snapshots__/useAtomSelector.test.tsx.snap
- packages/react/test/utils/ecosystem.ts
- packages/stores/src/AtomInstance.ts
Zedux core has never needed to track timestamps when nodes are created. It's always been possible for plugins to implement this and will be much easier with the new plugin system in Zedux v2.
Since this functionality is so rarely useful, it isn't worth the constant overhead, especially in prod. We'll make sure plugins can implement this. I'll also probably implement it as part of the official Zedux dev tools.
`ecosystem._idGenerator.now` is gone as well as the `createdAt` property on all atom instances and graph edges. Instead, a plugin can listen to:
- (v1) `edgeCreated`, `evaluationFinished`, and `statusChanged` plugin actions
- (v2) `edge` (which we're possibly renaming to `link`), `runStart`, and `cycle` ecosystem events.
and either track creation time in a separate WeakMap/similar or …
> feat(atoms)!: remove `createdAt` timestamp tracking

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
- packages/stores/package.json
Increment monorepo package versions and update the CHANGELOG for version 2.0.0-beta.1.
> release: v2.0.0-beta.1

- package.json
- packages/atoms/src/classes/Selectors.ts
- packages/atoms/src/classes/instances/AtomInstance.ts
- packages/atoms/src/types/index.ts
- packages/react/src/hooks/useAtomInstance.ts
- packages/react/src/hooks/useAtomSelector.ts
- packages/react/test/units/__snapshots__/useAtomSelector.test.tsx.snap
- packages/react/test/units/useAtomSelector.test.tsx
- yarn.lock
@affects atoms, react
Thanks to the excellent, simple repro by @joprice in #152, I was able to get a much better handle on React 18's StrictMode bugs that many previous Zedux versions failed to fully work around.
This takes a previous idea of using WeakRefs to track garbage cache items and graph edges created by StrictMode. Build on that idea by making each WeakRef reference a node in a singly-linked list of WeakRefs that walk back through StrictMode's destruction.
As soon as any hook's `useEffect` runs, walk back through the list its last node has access to and clean up everything node until reaching any that have materialized - any real, non-StrictMode-junk nodes will run after the first node. They'll point back to valid nodes, bailing out immediately.
Iterate up through the linked list …
> fix: use singly-linked WeakRefs to clean up React 18 StrictMode trash

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
Increment monorepo package versions and update the CHANGELOG for version 1.3.1.
> release: v1.3.1

- packages/react/src/hooks/useAtomInstance.ts
- packages/react/src/hooks/useAtomSelector.ts
Certain React rendering sequences can apparently cause the singly-linked WeakRef list added in #154 to reference in circles. This causes the `while` loop cleaning up weak refs to run infinitely. This can only happen in `useAtomSelector`'s `prevCache` linked list, not `useAtomSelector`'s or `useAtomInstance`'s `prevEdge` linked lists.
Mark each node as materialized when it's visited to kick out of the while loop when it hits a node it's already seen. Verify this fixes the problem for `useAtomSelector`'s `prevCache` linked list. Do the same for the `prevEdge` linked lists in `useAtomSelector` and `useAtomInstance` just in case something we change later possibly introduces the same problem for those.
I will add repro tests in a separate PR
Resolves #160
> fix(react): guard against circular `prevCache` refs in `useAtomSelector`

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
Increment monorepo package versions and update the CHANGELOG for version 1.3.2.
> release: v1.3.2

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
Increment monorepo package versions and update the CHANGELOG for version 1.3.3.
> release: v1.3.3

- packages/atoms/src/classes/SelectorInstance.ts
- packages/atoms/src/injectors/injectMemo.ts
- packages/atoms/src/utils/graph.ts
- packages/react/test/integrations/injectors.test.tsx
- packages/react/test/stores/injectors.test.tsx
When called with no deps, `injectMemo` currently behaves like React's `useMemo` - it runs on every evaluation. This is pointless, obviously. Instead of mimicking React, we can add a new behavior that aligns with Zedux's new status as an official signals implementation:
When called with no deps, make `injectMemo`'s callback a new reactive context that tracks signal usages. This creates a new SelectorInstance under the hood that observes all used signals. Make the calling atom, in turn, an observer of that selector.
This usage comes with some caveats:
- The function reference passed to `injectMemo` is never updated. It can't be, or that would defeat the point of `injectMemo` since, technically, every time you call `injectMemo`, you typically pass a new function reference. That means any …
> feat(atoms)!: make `injectMemo` reactive when no deps are passed

- packages/atoms/src/classes/Ecosystem.ts
- packages/atoms/src/classes/GraphNode.ts
- packages/atoms/src/classes/IdGenerator.ts
- packages/atoms/src/classes/SelectorInstance.ts
- packages/atoms/src/classes/instances/AtomInstance.ts
- packages/atoms/src/utils/ecosystem.ts
- packages/atoms/src/utils/graph.ts
- packages/react/README.md
- packages/react/src/hooks/useAtomInstance.ts
- packages/react/src/hooks/useAtomSelector.ts
- packages/react/src/index.ts
- packages/react/src/inject.ts
- packages/react/src/utils.ts
- packages/react/test/integrations/__snapshots__/scoped-atoms.test.tsx.snap
- packages/react/test/integrations/ecosystem.test.tsx
- packages/react/test/integrations/plugins.test.tsx
- packages/react/test/integrations/scoped-atoms.test.tsx
- packages/react/test/units/Ecosystem.test.tsx
- packages/stores/src/AtomInstance.ts
@affects atoms, react, stores
I spent a few days exploring the `inject` utility discussed in #129. I was mostly just experimenting but I somehow actually knocked the whole thing out. It is pretty complex but so powerful that I really want to start using it now 💪 . So here we are.
Implement `inject`. This is a new injector that is a thin wrapper around React's `use` util (hence the name) but with a few key differences:
- `inject` does not support promises. It will if we ever introduce async atoms (which are currently waiting on the TC39 async context proposal).
- `inject` accepts atom templates and will pull a provided instance from `<AtomProvider>`.
- `inject` should not be used conditionally, though it can be used in loops, unlike normal injectors, as long as a given context is passed to …
> feat: implement scoped atoms, `inject`, and `ecosystem.withScope`

- packages/atoms/src/classes/GraphNode.ts
- packages/atoms/src/classes/MappedSignal.ts
- packages/atoms/src/classes/SelectorInstance.ts
- packages/atoms/src/classes/Signal.ts
- packages/atoms/src/classes/instances/AtomInstance.ts
- packages/atoms/src/index.ts
- packages/atoms/src/injectors/injectPrevDescriptor.ts
- packages/atoms/src/types/index.ts
- packages/atoms/src/utils/ecosystem.ts
- packages/atoms/src/utils/general.ts
- packages/atoms/src/utils/graph.ts
- packages/react/src/hooks/useAtomContext.ts
- packages/react/src/hooks/useAtomInstance.ts
- packages/react/src/hooks/useAtomSelector.ts
- packages/react/test/integrations/events.test.tsx
- packages/react/test/integrations/lifecycle.test.tsx
- packages/react/test/units/SelectorInstance.test.tsx
- packages/react/test/utils/ecosystem.ts
- packages/stores/src/AtomInstance.ts
@affects atoms, react, stores
The `l`ifecycleStatus property of graph nodes is already obfuscated, what with being a single-letter property. We can get a micro performance and build size boost by further obfuscating its value to be a number rather than a full status string.
Since this makes the property unreadable, add a new `status` getter property to all graph nodes. This reads from `this.l`ifecycleStatus and translates it to the old `Active | Initializing | Stale | Destroyed` strings.
This is technically a breaking change over previous v2 beta versions since `node.l` is an obfuscated number now. Use `node.status` instead.
> feat!: add `status` getter property to graph nodes

- packages/atoms/src/classes/Ecosystem.ts
- packages/atoms/src/classes/MappedSignal.ts
- packages/atoms/src/classes/Scheduler.ts
- packages/atoms/src/classes/Signal.ts
- packages/atoms/src/utils/ecosystem.ts
- packages/core/src/types.ts
- packages/react/test/integrations/mapped-signals.test.tsx
- packages/react/test/integrations/signals.test.tsx
@affects atoms, core
Just like React, Zedux allows updating state synchronously during node evaluation. With stores, it was possible to prevent such state updates from triggering a reevaluation because stores propagate the change immediately to all child stores. That means you wouldn't see state tearing between composed stores in the atom.
With signals, on the other hand, we can't propagate the change to observers until after the current node finishes evaluating. That means composed signals (via `injectMappedSignal`) can get out of sync with signals they're composed of. Example:
```ts
const tearingAtom = atom('tearing', () => {
const signal = injectSignal('initial state')
const mappedSignal = injectMappedSignal({ signal })
signal.set('new state')
signal.get() // 'new state' …
```
> fix: defer state changes during node evaluation

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
- packages/stores/package.json
Increment monorepo package versions and update the CHANGELOG for version 2.0.0-beta.2.
> release: v2.0.0-beta.2

- packages/atoms/src/classes/MappedSignal.ts
- packages/atoms/src/classes/Signal.ts
- packages/atoms/src/classes/templates/AtomTemplate.ts
- packages/atoms/src/classes/templates/IonTemplate.ts
- packages/atoms/src/factories/atom.ts
- packages/atoms/src/factories/ion.ts
- packages/atoms/src/types/atoms.ts
- packages/atoms/src/utils/ecosystem.ts
- packages/atoms/src/utils/events.ts
- packages/atoms/src/utils/graph.ts
- packages/react/package.json
- packages/react/src/inject.ts
- packages/react/test/integrations/scoped-atoms.test.tsx
- packages/react/test/stores/dependency-injection.test.tsx
- packages/stores/src/AtomInstance.ts
- packages/stores/src/AtomTemplate.ts
- packages/stores/src/IonTemplate.ts
- packages/stores/src/atom.ts
- packages/stores/src/ion.ts
- packages/stores/src/types.ts
@affects atoms, react, stores
Finally using Zedux v2 in a real app, I quickly found several types we don't have tests for that are either broken or make it unnecessarily difficult to type functions that work with Zedux objects.
Also, `signal.mutate` was still claiming it returns a tuple, even though I got rid of that capability in #175.
The build of the last beta release also had a circular import in it that prevented `GraphNode` from being defined before `Signal` tried to extend it. Fix that
This will need follow-up work to test as much of this as possible - if we can get regression tests for all these changes, it'll guarantee a smoother process to upgrade Zedux in our apps in the future.
This includes one breaking change that we really should have changed a long time ago - the …
> fix!: fix some types, return values, and relative imports

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
- packages/stores/package.json
Increment monorepo package versions and update the CHANGELOG for version 2.0.0-beta.3.
> release: v2.0.0-beta.3

- packages/atoms/src/types/index.ts
- packages/stores/src/AtomTemplate.ts
@affects atoms, stores
Follow-up to #178, some more types are too strict and should just be `any`. These don't turn off types for any of Zedux's APIs, they just allow the user to extend them without TS complaining unnecessarily about a mismatch.
> fix: fix some more v2 types

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
- packages/stores/package.json
Increment monorepo package versions and update the CHANGELOG for version 2.0.0-beta.4.
> release: v2.0.0-beta.4

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
Increment monorepo package versions and update the CHANGELOG for version 1.3.4.
> release: v1.3.4

- packages/atoms/src/classes/AtomApi.ts
- packages/atoms/src/classes/Scheduler.ts
- packages/atoms/src/classes/instances/AtomInstance.ts
- packages/atoms/src/factories/api.ts
- packages/atoms/src/injectors/injectCallback.ts
- packages/atoms/src/types/index.ts
- packages/react/test/integrations/__snapshots__/graph.test.tsx.snap
- packages/react/test/integrations/graph.test.tsx
- packages/react/test/integrations/scoped-atoms.test.tsx
During some initial playtesting with the new scoped atoms feature, I found one of the primary pain points with it is that exported functions of scoped atoms have to remember to wrap re-getting of atoms they depend on in `ecosystem.withScope`. We can do this automatically.
Wrap exported arrow functions (only arrow functions - functions with a `.prototype` can be constructed with the `new` keyword, we don't want to mess with those) as well as `injectCallback` functions in `ecosystem.withScope` calls _if_ their containing atom is scoped.
Also wrap exports in `ecosystem.batch` while we're at it. We had this before, but the logic was in the AtomInstance class, which was wrong. So we removed it and it's been on my todo list to revisit. Now it's revisited.
Add a `wrap` option as the second …
> feat(atoms): wrap exports and `injectCallback` in current atom's scope

- packages/atoms/src/classes/Ecosystem.ts
- packages/atoms/src/classes/GraphNode.ts
- packages/atoms/src/classes/templates/AtomTemplateBase.ts
- packages/atoms/src/types/index.ts
- packages/atoms/src/utils/ecosystem.ts
- packages/react/test/integrations/ecosystem.test.tsx
- packages/react/test/stores/ssr.test.tsx
- packages/react/test/units/Ecosystem.test.tsx
Atoms have a feature called "flags". These are arbitrary strings that add a list of searchable attributes to an atom. In other words, tags.
I'm not sure why this feature was ever called "flags". Possibly 'cause I created them around the same time I added the bitwise edge flags. Or maybe 'cause one of their purposes is to raise a warning ("flag") for unsafe atoms.
Regardless, tags is a more appropriate name for them.
This feature is probably not used much, but renaming the config option is still, of course, a breaking change.
```ts
- atom('myAtomKey', myStateFactory, { flags: ['browser-only'] }) // before
+ atom('myAtomKey', myStateFactory, { tags: ['browser-only'] }) // after
```
> feat(atoms)!: rename atom flags to tags

- packages/atoms/src/classes/instances/AtomInstance.ts
- packages/immer/package.json
- packages/immer/src/injectImmerStore.ts
- packages/machines/package.json
- packages/machines/src/injectMachineStore.ts
- packages/react/src/hooks/useAtomInstance.ts
- packages/stores/src/AtomInstance.ts
- packages/stores/src/injectStore.ts
- packages/stores/src/types.ts
@affects atoms, immer, machines, react, stores
The atom instance `._promiseStatus` and `._promiseError` properties are meant to be read by users. They shouldn't be underscore-prefixed.
Also the `._isEvaluating` property is only relevant for store atoms - signals-based atoms don't need to buffer store updates during evaluation. Move that to the store-based `AtomInstance` class.
`AtomInstance#_promiseStatus` is renamed to `AtomInstance#promiseStatus`
`AtomInstance#_promiseError` is renamed to `AtomInstance#promiseError`
`AtomInstance#_isEvaluating` is gone on the signals-based `AtomInstance` class (in the `@zedux/atoms` and therefore `@zedux/react` packages). It's moved to the store-based `AtomInstance` class in the `@zedux/stores` package.
The `@zedux/stores` package also exports a new …
> feat!: de-underscore-prefix atom promise properties; move `_isEvaluating` to store atoms

- packages/atoms/src/classes/Ecosystem.ts
- packages/atoms/src/classes/GraphNode.ts
- packages/atoms/src/classes/instances/AtomInstance.ts
- packages/atoms/src/factories/api.ts
- packages/atoms/src/types/index.ts
- packages/atoms/src/utils/evaluationContext.ts
- packages/atoms/src/utils/graph.ts
- packages/core/src/utils/types.ts
- packages/react/src/hooks/useAtomSelector.ts
- packages/react/test/integrations/__snapshots__/ecosystem.test.tsx.snap
- packages/react/test/integrations/__snapshots__/graph.test.tsx.snap
- packages/react/test/integrations/injectors.test.tsx
- packages/react/test/integrations/selection.test.tsx
- packages/react/test/stores/__snapshots__/graph.test.tsx.snap
- packages/react/test/stores/injectors.test.tsx
- packages/react/test/units/SelectorInstance.test.tsx
- packages/react/test/units/useAtomSelector.test.tsx
- packages/stores/src/AtomInstance.ts
- packages/stores/src/api.ts
In v2, a graph node's "dependencies" are called "sources" and "dependents" are called "observers". This is consistent with other signals libs and I find it clearer. Reword mostly code comments to reflect this.
The only non-code-comment affected by this is the objects returned by `ecosystem.viewGraph`. Those had `dependencies` and `dependents` keys. Rename those to `sources` and `observers` respectively.
> feat(atoms)!: use consistent terminology for observers and sources

- packages/react/package.json
- packages/react/src/utils.ts
We can use React's default export to check if React 19's `use` util exists before using it. Throw an error if it doesn't to let the user know that scoped atoms can only hook into React context in React 19. If you can't upgrade to React 19, you can still use scoped atoms manually via `ecosystem.withScope`.
With this PR, Zedux v2 now works in React 18 non-strict-mode, you just probably won't want to use scoped atoms until upgrading to React 19.
> feat(react): check for `React.use` before using; partially support React 18

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
- packages/stores/package.json
Increment monorepo package versions and update the CHANGELOG for version 2.0.0-beta.5.
> release: v2.0.0-beta.5

- bench/src/frameworks/zedux.ts
- packages/atoms/src/classes/Ecosystem.ts
- packages/atoms/src/classes/GraphNode.ts
- packages/atoms/src/classes/MappedSignal.ts
- packages/atoms/src/classes/SelectorInstance.ts
- packages/atoms/src/classes/Signal.ts
- packages/atoms/src/classes/instances/AtomInstance.ts
- packages/atoms/src/classes/schedulers/SchedulerBase.ts
- packages/atoms/src/classes/schedulers/SyncScheduler.ts
- packages/atoms/src/index.ts
- packages/atoms/src/utils/evaluationContext.ts
- packages/atoms/src/utils/graph.ts
- packages/atoms/src/utils/selectors.ts
- packages/core/src/utils/types.ts
- packages/stores/src/AtomInstance.ts
@affects atoms, core, stores
At 1400+ ms, Zedux's `broadPropagation` benchmark score, while >4x faster than Jotai, is still far behind most other signals libraries. This is because Zedux uses a scheduler for everything. At best, this is an O(n log n) algorithm. Most other signals libs use an O(n) (2n to be precise) push-pull algorithm.
The "phase 2" of the graph algorithm change I've been talking about involves switching us to a similar model for normal graph updates. But rather than bail immediately, we should optimize this algorithm first.
The difference between O(n) and O(n log n) shouldn't be as extreme as it looks right now. In fact, we would be able to micro-optimize Zedux so much that the difference is imperceptible. However, our scheduler algorithm must use a dense JS array. And …
> refactor: micro optimize broad graph updates and node creation

- packages/atoms/src/classes/Ecosystem.ts
- packages/atoms/src/classes/GraphNode.ts
- packages/atoms/src/types/index.ts
- packages/react/test/integrations/ecosystem.test.tsx
- packages/react/test/integrations/graph.test.tsx
- packages/react/test/integrations/scoped-atoms.test.tsx
- packages/react/test/stores/graph.test.tsx
- packages/react/test/stores/ssr.test.tsx
- packages/react/test/units/Ecosystem.test.tsx
- packages/react/test/units/SelectorInstance.test.tsx
Zedux's "built-in devtools", `ecosystem.findAll` and `ecosystem.dehydrate` received some upgrades for v2. But hitherto, there was still no good way to make them return only atoms.
While #201 made all other node types easier to search for by simply passing an `@` prefix, it did not give atoms an `@atom` prefix. I think it still makes sense that these methods should accept `@atom` specifically.
So: Give both `findAll` and `dehydrate` an overload for TS auto completion of the node types. Handle the `@atom` string specifically.
```ts
ecosystem.findAll('@atom') // get a list of all atom nodes
ecosystem.findAll('@selector') // get a list of all selector nodes
ecosystem.findAll('@component') // get a list of all React component nodes
ecosystem.findAll({ include: ['@atom', '@signal'] }) // get a …
```
> feat(atoms)!: support `@atom` node type filter in `findAll` and `dehydrate`

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
- packages/stores/package.json
Increment monorepo package versions and update the CHANGELOG for version 2.0.0-beta.7.
> release: v2.0.0-beta.7

- packages/atoms/src/classes/AtomApi.ts
- packages/atoms/src/injectors/injectCallback.ts
- packages/react/test/integrations/injectors.test.tsx
- packages/react/test/units/AtomApi.test.tsx
make `injectCallback` and wrapped exports in AtomAPIs set the wrapping function's name to the name of the wrapped function. Add tests.
> feat(atoms): make wrapper functions reuse wrapped function names

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
- packages/stores/package.json
Increment monorepo package versions and update the CHANGELOG for version 2.0.0-beta.8.
> release: v2.0.0-beta.8

- docs/docs/migrations/v2.mdx
- packages/atoms/src/classes/Ecosystem.ts
- packages/atoms/src/classes/ZeduxNode.ts
- packages/atoms/src/classes/instances/AtomInstance.ts
- packages/atoms/src/classes/templates/AtomTemplate.ts
- packages/atoms/src/classes/templates/AtomTemplateBase.ts
- packages/atoms/src/classes/templates/IonTemplate.ts
- packages/atoms/src/types/index.ts
- packages/atoms/src/utils/ecosystem.ts
- packages/atoms/src/utils/graph.ts
- packages/react/test/integrations/scoped-atoms.test.tsx
- packages/react/test/legacy-types.test.tsx
- packages/react/test/types.test.tsx
- packages/stores/src/AtomInstance.ts
- packages/stores/src/AtomTemplate.ts
- packages/stores/src/IonTemplate.ts
@affects atoms, stores
With the introduction of scoped atoms came the concept of scoped ids. These `@scope()`-suffixed ids can currently only be generated automatically by Zedux internals.
Expose a way to create scoped ids via the existing `getInstanceId` method on `AtomTemplateBase`. Pass an optional third object parameter with a `scope` map pointing contexts to their contextual values that should be added to the id. Also rename `getInstanceId` to `getNodeId` to match the new nomenclature.
```ts
import { atom, createEcosystem } from '@zedux/react'
const ecosystem = createEcosystem()
const contextAtom = atom('context', 'example state')
const scopedAtom = atom('scoped', () => {
inject(contextAtom)
})
const scope = new Map([
[contextAtom, ecosystem.getNode(contextAtom)]
])
const id = …
```
> feat!: rename `getInstanceId` to `getNodeId` and add a `scope` option

- docs/docs/migrations/v2.mdx
- packages/atoms/src/classes/Ecosystem.ts
- packages/atoms/src/classes/ZeduxNode.ts
- packages/atoms/src/classes/instances/AtomInstance.ts
- packages/atoms/src/classes/templates/IonTemplate.ts
- packages/atoms/src/factories/ion.ts
- packages/atoms/src/injectors/injectAtomState.ts
- packages/atoms/src/types/atoms.ts
- packages/atoms/src/types/index.ts
- packages/atoms/src/utils/ecosystem.ts
- packages/atoms/src/utils/selectors.ts
- packages/react/src/hooks/useAtomSelector.ts
- packages/react/src/hooks/useAtomState.ts
- packages/react/test/integrations/ecosystem.test.tsx
- packages/react/test/integrations/lifecycle.test.tsx
- packages/react/test/integrations/scoped-atoms.test.tsx
- packages/react/test/integrations/selection.test.tsx
- packages/react/test/units/useAtomState.test.tsx
- packages/stores/src/AtomInstance.ts
- packages/stores/src/types.ts
@affects atoms, stores
There are just a few last things to round up for Zedux v2. Knock them all out.
Add an array overload to `ecosystem.findAll` that's a shorthand for `.findAll({ include: [...mySearchList] })`. This is especially useful now that all node types can be returned.
Add a type overload to `ecosystem.findAll` so editors autocomplete with the new `@`-prefixed strings by default. This gives some very sleek DX - type `ecosystem.findAll('` and you'll see `@atom` as the first suggestion, which should be the most common. Same goes for the new array overload.
Deprecate the old store-based AtomInstance `.setState` function property. Prefer `.set` instead - it does the same thing for store-based atoms, but will make it easier to migrate to signals-based atoms.
Remove the …
> feat!: improve `findAll`, ions, and clean up types, properties, and deprecations

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
- packages/stores/package.json
Increment monorepo package versions and update the CHANGELOG for version 2.0.0-rc.0.
> release: v2.0.0-rc.0

- docs/docs/migrations/v2.mdx
- packages/core/src/api/createStore.ts
- packages/core/src/types.ts
- packages/core/src/utils/scheduler.ts
- packages/machines/src/MachineStore.ts
- packages/stores/src/StoreAtomInstance.ts
@affects core, machines, stores
One more type from the `@zedux/core` package needs to be renamed for full interoperability with the `@zedux/atoms` package.
Rename the core package's `Settable` type to `StoreSettable`. The `Settable` type in the `@zedux/atoms` package is unchanged.
This is technically a breaking change for TS users, but I'm classifying it as a bug since it caused problems for us.
> fix: rename core package `Settable` to `StoreSettable`

- packages/atoms/src/injectors/injectEffect.ts
- packages/react/test/integrations/lifecycle.test.tsx
`injectEffect` schedules async jobs that can be upgraded to sync jobs. But it currently only tries to unschedule jobs from the async scheduler. This means that when atoms are created outside React and throw on initial evaluation, the effects remain scheduled in the syncScheduler and will run later, when something flushes that scheduler.
Detect which scheduler will be used in `injectEffect` and unschedule from the correct scheduler.
> fix(atoms): unschedule effects from the right scheduler

- packages/react/src/hooks/useAtomContext.ts
- packages/react/test/integrations/react-context.test.tsx
When passing default params to `useAtomContext`, Zedux gets or creates the instance for those params if no instance is provided. This operation currently happens without access to scope and without flagging the current context as unsafe for effects to run immediately.
So provide the react context scope to the `ecosystem.getInstance` call in `useAtomContext`. Also switch to `getNode`. The react context scope also automatically (currently) flags the context as unsafe for effects. Add a test for that.
> fix(react): use scope in `useAtomContext` when using default params

- packages/react/src/components/AtomProvider.tsx
- packages/react/test/integrations/react-context.test.tsx
- packages/react/test/integrations/scoped-atoms.test.tsx
In tests, `AtomProvider` is often rendered at the top-level, e.g. in a storybook setup function. Currently, this means you have to either create a wrapper component for each test or use a global ecosystem to get an instance statically - outside React - that you then provide.
The former approach involves boilerplate.
The latter approach can cause problems if the provided atom has `ttl: 0` and consuming components unmount, destroying the provided atom. The AtomProvider will continue to provide the destroyed atom indefinitely.
To better handle this, make `AtomProvider` register a static dependency on the provided atom instance. Also introduce new function overloads to `AtomProvider`'s `instance` and `instances` props.
The passed callback receives the ecosystem as its first parameter and …
> feat(react): add function overloads to `AtomProvider` props

- packages/atoms/src/classes/MappedSignal.ts
- packages/atoms/src/injectors/injectMappedSignal.ts
- packages/react/test/integrations/mapped-signals.test.tsx
`MappedSignal#set` currently handles the case where a single call causes updates in multiple inner signals. It also filters down which events to pass to each inner signal.
`MappedSignal#send` is missing these features - when an event is sent directly to the wrapping signal that reaches multiple inner signals, each inner signal will propagate the event again, back up to the mapped signal and its observers. `MappedSignal#send` also does not support the object overload of `Signal#send` even though the types suggest it does.
Fix those cases. Make `MappedSignal#send` handle the object overload. Make it only propagate each event to its own observers once. Also give mapped signals the ability to specify their own events. Add tests for all of that.
> feat(atoms): dedupe mapped signal events that reach multiple children

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
- packages/stores/package.json
Increment monorepo package versions and update the CHANGELOG for version 2.0.0-rc.1.
> release: v2.0.0-rc.1

- packages/react/src/components/AtomProvider.tsx
I missed an automatically added import path in #219 that's importing from a directory barrel file. The esm build requires it import from the exact file. Fix that.
> fix(react): fix import path in `AtomProvider`

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
- packages/stores/package.json
Increment monorepo package versions and update the CHANGELOG for version 2.0.0-rc.2.
> release: v2.0.0-rc.2

- packages/core/src/api/createStore.ts
- packages/react/test/stores/graph.test.tsx
- packages/stores/src/StoreAtomInstance.ts
@affects core, stores
When store and atom state updates get interwoven in recursive atom/store trees, the store scheduler needs to fully flush before any atom updates run to prevent atom updates from happening out of order.
Kick off the atom scheduler before any store updates.
> fix: make stores scheduler kick off the atoms scheduler first

- packages/react/src/hooks/useReactComponentId.ts
Since we technically still support React 18 outside StrictMode, add the React 18 component name reading code back in.
This makes use of React's forbidden internals, but does so in a completely safe way. If React changes, Zedux will continue to work, just without this DX improvement.
> feat(react): support react 18 component names

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
- packages/stores/package.json
Increment monorepo package versions and update the CHANGELOG for version 2.0.0-rc.3.
> release: v2.0.0-rc.3

- packages/react/src/hooks/useAtomInstance.ts
- packages/react/test/integrations/graph.test.tsx
When used to create static deps, `useAtomInstance` doesn't currently rerender the component when StrictMode's extra useEffect cleanup destroys a `ttl: 0` atom. Fix that.
There's a check in there that's supposed to catch this (`instance.l === zi.D`estroyed), but another bug fix made it so the `instance` reference here is never destroyed. Just update the check to use the instance that was actually returned by the hook call during render.
Reproduce in a regression test and confirm the fix.
> fix(react): make static hooks always rerender on destroy

- bench/src/index.ts
- packages/atoms/src/classes/Ecosystem.ts
- packages/atoms/src/classes/ZeduxNode.ts
- packages/atoms/src/classes/schedulers/SyncScheduler.ts
- packages/atoms/src/types/index.ts
- packages/atoms/src/utils/graph.ts
- packages/react/test/integrations/__snapshots__/graph.test.tsx.snap
- packages/react/test/stores/__snapshots__/graph.test.tsx.snap
- packages/react/test/utils/ecosystem.ts
Zedux v2 has made huge strides in perf improvements thanks to the [js-reactivity-benchmark benchmarks](https://github.com/milomg/js-reactivity-benchmark). However, there's one last benchmark category that Zedux still struggles with: The `dynamicBench` category.
Zedux performs well on all but the last, "very dynamic" benchmark. While it's super contrived, probing an area where Zedux purposefully frontloads work due to how all real usages work, Zedux's performance on it is poor enough that it merits revisiting.
The benchmark constantly switches node dependencies around in a moderately-deep graph. Real nodes never do that - you define a node's deps and maybe switch a couple around here or there depending on user actions, feature switches, etc.
Again, super contrived, still, Zedux can take …
> feat(atoms): lazily recalculate node weights

- docs/docs/migrations/v2.mdx
- packages/atoms/src/factories/atom.ts
- packages/atoms/src/injectors/injectPromise.ts
- packages/atoms/src/types/atoms.ts
- packages/atoms/src/types/index.ts
- packages/atoms/src/utils/promiseUtils.ts
- packages/react/src/hooks/useAtomState.ts
- packages/react/src/hooks/useAtomValue.ts
- packages/react/test/integrations/promises.test.tsx
- packages/react/test/integrations/suspense.test.tsx
- packages/react/test/snippets/suspense.tsx
- packages/react/test/stores/injectStorePromise.test.tsx
- packages/stores/src/injectStorePromise.ts
- packages/stores/src/types.ts
@affects atoms, react, stores
Implement all `injectPromise` improvements discussed in #220 for Zedux v2, with one change: Instead of passing the full `dataSignal` to the callback function, pass the dataSignal's current value as `prevData`.
After digging in, I saw this change was necessary for two reasons:
- TS infers the callback's return value as `unknown`, even when using `NoInfer` on the dataSignal's type. With `prevData` and `NoInfer`, TS also infers `unknown`, but it's much easier to manually type `prevData` than `dataSignal` to fix it. If you don't actually use `prevData`, inference works as normal. Since it should be rare that you need `prevData`, I'm fine requiring manual typing when you do.
- It becomes confusing that the value returned from the promise factory overwrites the …
> feat!: improve `injectPromise` - add `dataSignal`, `initialData`, `ZeduxPromise`

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
- packages/stores/package.json
Increment monorepo package versions and update the CHANGELOG for version 2.0.0-rc.5.
> release: v2.0.0-rc.5

- packages/atoms/src/injectors/injectEffect.ts
- packages/react/test/integrations/timing.test.tsx
`injectEffect` can now upgrade to use the SyncScheduler instead of the AsyncScheduler when its atom evaluates outside React.
When that happens, any state updates that the effect triggers synchronously will be "batched" since the scheduler is flushing when the effect runs. But when using the AsyncScheduler, nothing is batched since those state updates are added to the SyncScheduler which is not flushing in this case.
Fix this by making `injectEffect` wrap its callback in an `ecosystem.batch` call, ensuring the callback is always batched. Effects often trigger async flows, meaning any later updates won't be batched, but that's fine; the important thing is that behavior is consistent regardless which scheduler is used.
> feat(atoms): consistently batch effect callbacks

- packages/atoms/src/injectors/injectMemo.ts
- packages/react/test/integrations/__snapshots__/injectors.test.tsx.snap
- packages/react/test/integrations/injectors.test.tsx
`@memo` nodes are the only nodes not added to `ecosystem.n`, which is counter-intuitive, ruins Zedux's perfect cache management, and can also hurt dev tools.
Add them to `ecosystem.n` and update existing tests to take ecosystem snapshots, ensuring the `@memo` nodes are present.
> feat(atoms): add memos to `ecosystem.n` for cache management

- packages/atoms/src/classes/Ecosystem.ts
- packages/atoms/src/utils/ecosystem.ts
- packages/atoms/src/utils/events.ts
- packages/atoms/src/utils/graph.ts
- packages/react/test/integrations/plugins.test.tsx
The `runStart` and `runEnd` events need to be sent to ecosystem event listeners immediately. Their primary purpose is timing atom/selector evaluation. Currently, they're batched along with any other ecosystem events and sent all at once at the end of the scheduler flush.
Since some events need to be sent immediately, make all ecosystem events notify ecosystem event listeners immediately. Completely remove all ecosystem event scheduling. I'd rather do this than have the behavior inconsistent.
Unfortunately, this means the original benefit of scheduling ecosystem events is gone. I scheduled them originally to prevent ecosystem event listeners from receiving events during React renders. That would allow them to set React state synchronously after receiving events.
Rather than make plugin …
> feat(atoms)!: send ecosystem events immediately

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
- packages/stores/package.json
Increment monorepo package versions and update the CHANGELOG for version 2.0.0-rc.6.
> release: v2.0.0-rc.6

- packages/atoms/src/injectors/injectPromise.ts
- packages/react/test/types.test.tsx
- packages/stores/src/injectStorePromise.ts
The new `injectPromise` improvements could also do with some better type overloads that recognize the `initialData` config option specifically. When specified, the resulting `data` is never `undefined`.
Add overloads that reflect this, reducing the need for nullish checks when using the returned `dataSignal`'s value or the `signal`'s (for `injectPromise`) or `store`'s (for `injectStorePromise`) `data` value.
> feat: improve `injectPromise` and `injectStorePromise` type overloads

- packages/atoms/src/factories/api.ts
- packages/atoms/src/factories/atom.ts
- packages/atoms/src/factories/ion.ts
- packages/atoms/src/injectors/injectPromise.ts
- packages/atoms/src/types/atoms.ts
- packages/atoms/src/types/index.ts
- packages/react/test/integrations/suspense.test.tsx
- packages/react/test/legacy-types.test.tsx
- packages/react/test/types.test.tsx
- packages/stores/src/injectStorePromise.ts
- packages/stores/src/storeApi.ts
- packages/stores/src/storeAtom.ts
- packages/stores/src/storeIon.ts
@affects atoms, stores
Ion instances aren't currently accepted as valid signals for the `api` factory. Also the ZeduxPromise should not be used to infer the state type of nodes, since the node's promise and state can be unrelated.
Fix both of those and improve some other overloads, type helpers, and tests.
> fix: improve types for ions and promises in atoms and atom apis

- packages/atoms/src/classes/Ecosystem.ts
- packages/atoms/src/types/index.ts
- packages/react/test/units/Ecosystem.test.tsx
The return type of `Ecosystem#getOnce` was copied from `Ecosystem#getNodeOnce` and never changed. This means `getOnce` thinks it returns a node instead of a node's value. Fix this and make sure the tests verify the type.
Resolves #246.
> fix(atoms): correct the return type of `Ecosystem#getNode`

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
- packages/stores/package.json
Increment monorepo package versions and update the CHANGELOG for version 2.0.0-rc.8.
> release: v2.0.0-rc.8

- packages/atoms/src/classes/Ecosystem.ts
- packages/atoms/src/classes/MappedSignal.ts
- packages/atoms/src/injectors/injectMappedSignal.ts
- packages/atoms/src/injectors/injectPromise.ts
- packages/atoms/src/injectors/injectSignal.ts
- packages/atoms/src/types/index.ts
- packages/react/test/__snapshots__/types.test.tsx.snap
- packages/react/test/types.test.tsx
The event map generic on `ecosystem.signal`, `injectSignal`, `injectMappedSignal`, and `injectPromise` expects a map of event names to functions that return the event's payload type. This is because that's how declaring events with runtime objects and Zedux v2's `As` helper works - the `As` helper itself is a function. Passing a generic to it tell Zedux the payload type of the event.
However, when manually typing events via the event map generic on the 4 above APIs, this means you have to map each event name to a function type like so:
```ts
injectSignal<MyStateType, { myEventName: () => MyEventPayload }>(myState)
```
This feels weird. We should make this generic itself a map of event names to payloads, cutting out the middle-man function. The runtime overloads can still infer this …
> feat(atoms): make EventMap generics easier to pass manually

- packages/atoms/src/classes/ZeduxNode.ts
- packages/atoms/src/classes/schedulers/AsyncScheduler.ts
- packages/react/src/hooks/useAtomInstance.ts
- packages/react/test/integrations/events.test.tsx
- packages/react/test/units/__snapshots__/useAtomSelector.test.tsx.snap
- packages/react/test/units/useAtomSelector.test.tsx
@affects atoms, react
#232 introduced a bug in React StrictMode that tests were actually catching but I missed it in the snapshot output. On rerender, `useAtomInstance`'s `useEffect` can trigger an infinite destruction-recreation loop thanks to StrictMode's extra effect cleanup/rerun. Fix that by running cleanup in a microtask.
Expose a convenient way to use AsyncScheduler's existing `queueMicrotask` shim via a new `ecosystem.asyncScheduler.queue` method. Use that for the `useAtomInstance` fix.
> fix: add `asyncScheduler.queue`; fix strict mode atom destroy loop

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
- packages/stores/package.json
Increment monorepo package versions and update the CHANGELOG for version 2.0.0-rc.9.
> release: v2.0.0-rc.9

- CHANGELOG.md
- package.json
- packages/atoms/package.json
- packages/core/package.json
- packages/immer/package.json
- packages/machines/package.json
- packages/react/package.json
Increment monorepo package versions and update the CHANGELOG for version 1.3.5.
> release: v1.3.5

- packages/react/test/stores/atom-stores.test.tsx
- packages/stores/src/StoreAtomInstance.ts
There's an edge case with `StoreAtomInstance`s in v2 where subscribers to a store in a store atom can run before the store atom's `.v`alue property is synchronized with the store's own state. Since `storeAtomInstance.get` and `storeAtomInstance.getState` are just aliases for `store.getState`, those don't cause problems. However, `storeAtomInstance.getOnce` reads the `.v`alue directly, leading to a state tearing bug in that (probably rare) case.
See the new regression test, "nested store subscribers don't see state tearing", in `atom-stores.test.tsx` for more details on the exact setup where this state tearing was happening.
Fix the state tearing by keeping `storeAtomInstance.v`alue more immediately in sync with `storeAtomInstance.store._state` every time it changes. Add a regression test …
> fix(stores): prevent state tearing in nested storeAtom store subscribers
